### PR TITLE
Address Opsdir review comments.

### LINKED ISSUE #78: Address Opsdir review comments
Reviewer: Gyan Mishra
Review result: Not Ready

The TCP FSM is of course the most critical component of the transport.

It would be good to list all that is not included in the Yang model that exists
in the TCP MIB.  Also would be helpful as to reasons why.

I see mentioned that RTO is not part of the Yang model, however to be complete
I think it should be included.

The yang model seems to not have  all the TCP FSM states listed below:
Closed
Listen
SYN RCVD
SYN Sent
Established
FIN wait 1
FIN wait 2
Closing
Time wait
Close wait
Last Ack

Also the Yang model does not reference the TCP Flag bits set during state
changes in the FSM below as well as flag combinations for example for
establishment state you sent SYN, receive SYN/ACK, ACK

URG
ACK
PUSH
RESET
SYN
FIN

I also don’t see anything in the Yang model on TCP window and window scaling
and CWIN congestion control algorithm backoff.

Also I don’t see any mention in the Yang model about the well known port range
0-1023 and > 1023 anonymous port range for the TCP socket to be established.

Also mention about the TCP TCB control block.

Local IP Local Port
Remote IP Remote Port
Interface
Process
State
Local/Send window
Remote/Receive window
Send SQ Ack
Send SQ Un-ack
Send SQ Next
Not to be sent
Receive Next
RTT
Buffer pointer

### LINKED ISSUE #89: Use of Keep-alives
The use of keep-alives and the references to draft-ietf-netconf-tcp-client-server-12 need further thinking.

1. Keep-alives are a seldomly used TCP feature that is optional to implement. Is this really relevant to be included in this model?
2. Removing keep-alives (and the example) would remove the dependency to draft-ietf-netconf-tcp-client-server-12. Note that users of keep-alives could still use draft-ietf-netconf-tcp-client-server as needed.
4. A specific comment from Tom Petch on the keep-alive example: "The example uses port 80 which is traditionally insecure. A secure port might set a better example." If the example stays in the document, probably an alternative to port 80 should be used, as keep-alives are more typical for long-lived connections (e.g., port 22).

### PR DESCRIPTION
**Pull request by mjethanandani**
#78

### CODE REVIEW

**Review by michael-scharf — COMMENTED** [review]
Refarding the leaf state: I suggest to align the state engine closely with https://datatracker.ietf.org/doc/draft-ietf-tcpm-rfc793bis/.

This implies at first sight:
* The description could be copied 1:1 from rfc793bis in order to be consistent.
* The state "delete" should IMHO be removed. In YANG, this could better be realized, e.g., by an RPC. Yet, I am not sure whether specifying that RPC makes sense in the base version of this spec.
* The description regarding listen(2) should be shortened to remove MIB text.  For instance: 
"The value listen is included only for backward compatibility and should not be used. A        connection in 'listen' state should be present in the listener table."
* The description regarding delete(12) and RST can be removed
* The list can IMHO be all config false

For the tcp-listener-entry, the proposed solution looks reasonable at first sight.

But I think we need to analyze whether this problem is already solved in any other YANG model. I don't recall one, but it looks like a pretty basic modeling problem in a TCP/IP stack. Would this be something to be discussed on the NETMOD mailinglist (with TCPM in CC)?

**Comment by mjethanandani** [comment]
> Refarding the leaf state: I suggest to align the state engine closely with https://datatracker.ietf.org/doc/draft-ietf-tcpm-rfc793bis/.

Done

> 
> This implies at first sight:
> 
> * The description could be copied 1:1 from rfc793bis in order to be consistent.

Ok

> * The state "delete" should IMHO be removed. In YANG, this could better be realized, e.g., by an RPC. Yet, I am not sure whether specifying that RPC makes sense in the base version of this spec.

Agree. I do not think we should be using YANG to remove a connection from the connection table.

> * The description regarding listen(2) should be shortened to remove MIB text.  For instance:
>   "The value listen is included only for backward compatibility and should not be used. A        connection in 'listen' state should be present in the listener table."
> * The description regarding delete(12) and RST can be removed

I have removed almost all the text.

> * The list can IMHO be all config false

Ok

> 
> For the tcp-listener-entry, the proposed solution looks reasonable at first sight.
> 
> But I think we need to analyze whether this problem is already solved in any other YANG model. I don't recall one, but it looks like a pretty basic modeling problem in a TCP/IP stack. Would this be something to be discussed on the NETMOD mailinglist (with TCPM in CC)?

Which problem are you referring to? Modeling a connection table, deleting an entry from the connection table??

**Comment by mjethanandani** [comment]
@michael-scharf , I am not sure of the state 'closed'. Will a connection in that state appear in the connection table.

I also realized that I had put the tcp-listner-table under the 'connections' container. But that table exists independent of the connection table. Right?

**Comment by michael-scharf** [comment]
> @michael-scharf , I am not sure of the state 'closed'. Will a connection in that state appear in the connection table.

I doubt that a connection in state closed would appear, but it is one of the states of the very well-known state engine, and it was also used in the TCP MIB.

At first sight, I'd propose to keep the state. A comment could be added that connections in state closed may not appear in the list.
 
> I also realized that I had put the tcp-listner-table under the 'connections' container. But that table exists independent of the connection table. Right?

Yep. I'll comment on that separately.

**Comment by michael-scharf** [comment]
Comments on the listener modeling, after some further research:

* The list should probably be renamed, e.g., to "tcp-listener" or "tcp-listeners"
* The description includes MIB speak. Alternative: "A table containing information about a particular TCP listener."
* If we actually need a type (see below), I wonder if we could use "ip-version" from RFC 6991 instead of an own typedef
* I am not sure if the specific encoding in the MIB requiring an empty string is actually used.

A quick analysis of "ss" and "netstat" on Debian 11 reveals:
1. "netstat" mostly uses either IPv4 or IPv6 and probably IPv6 if both versions are supported
2. "ss" apparently uses a wildcard "*" in some cases.

It seems also possible to have *two* listener entries on the same port, one for IPv6 and one for IPv4. I have not figured out whether this is actually different to one entry with a wildcard.

At least the exact model selected for listener IP addresses may require a review by owners of running code on the TCPM list before moving forward.

And, yes, the listeners list is IMHO independent of the connection list.

**Pull request merged**
